### ISSUE TITLE
About xmap2ALLMAPSbed.pl

### ISSUE THREAD

**Issue by wyim-pgl** [Nucleomics-VIB/bionano-tools#2]
Dear Stephane,
Hello!,

I just checked this code and I don't know how it works.

Can you tell me a little bit about this? I have xmap and keys and others. But I don;t know how to apply this to ALLMAPS.

Thank you.
Won

**Comment by splaisan** [comment]
This just makes a bed which should fit allmaps requirements as described in their pages. I am sorry but cannot help you further with allmaps for which you will need to post on the developer's pagesBest


Sent from my smartphone.
-------- Original message --------From: Won Cheol Yim <notifications@github.com> Date: 11/5/17  01:21  (GMT+01:00) To: Nucleomics-VIB/bionano-tools <bionano-tools@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [Nucleomics-VIB/bionano-tools] About xmap2ALLMAPSbed.pl (#2) 
Dear Stephane,

Hello!,
I just checked this code and I don't know how it works.
Can you tell me a little bit about this? I have xmap and keys and others. But I don;t know how to apply this to ALLMAPS.
Thank you.

Won

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Nucleomics-VIB/bionano-tools","title":"Nucleomics-VIB/bionano-tools","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Nucleomics-VIB/bionano-tools"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"About xmap2ALLMAPSbed.pl (#2)"}],"action":{"name":"View Issue","url":"https://github.com/Nucleomics-VIB/bionano-tools/issues/2"}}}

**Comment by splaisan** [comment]
please have a look at **https://github.com/tanghaibao/jcvi/wiki/ALLMAPS:-How-to-use-different-types-of-genomic-maps** for potential use of the converted data
